name: Java CI with Maven Matrix

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and Check Test Coverage with Maven
        run: mvn -B verify --file pom.xml

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar-${{ matrix.os }}
          path: target/*.jar

      - name: Upload JaCoCo Coverage Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jacoco-html-report-${{ matrix.os }}
          path: target/site/jacoco/